#!/bin/sh

# script/server: Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

go-wrapper download
go-wrapper install

go-wrapper run --db-data-connection=$DB_DATA_CONNECTION --db-store-connection=$DB_STORE_CONNECTION --env=$APP_ENV
