#!/bin/sh

# script/server: Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

go-wrapper download
go-wrapper install
go get github.com/pilu/fresh

RUNNER_TMP_PATH=/tmp fresh
