#!/usr/bin/env sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

echo "==> Setup is started at…"
date "+%H:%M:%S"

echo "==> Instaling dependencies…"
yarn install

echo "==> Starting app…"
"$(yarn bin)"/ng serve --host 0.0.0.0 --port 4200
